title:            Aging Coder
description:      Random Musings on Technology
logo:             logo.png
disqus_shortname: agingcoder
share:            true
dropcap:		  true
comments:         true

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:              http://agingcoder.com

# Owner/author information
owner:
  name:           Kris Erickson
  avatar:         portrait.jpg
  email:          ksoncan34@yahoo.ca
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    The Aging Coder
  # Social networking links used in footer. Update and remove as you like.
  twitter:        ksoncan34
  github:         kriserickson
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+KrisEricksonLee

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-46763224-1
google_verify:      
bing_verify:

gems: [jekyll-paginate]

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Vancouver
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highliter: coderay
  syntax_highlighter_opts:
    coderay_line_numbers: nil
    enable_coderay: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "rakefile", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

